/**
 * Minimal JSON Schema -> TypeScript type emitter.
 *
 * Supports: object/properties/required, string, number, integer, boolean,
 * null, array/items, enum (literal union), oneOf/anyOf (union), type arrays
 * (union). Everything else falls back to `unknown`.
 */
export function jsonSchemaToTs(schema: unknown): string {
  if (schema === true) return "unknown";
  if (schema === null || typeof schema !== "object" || Array.isArray(schema)) {
    return "unknown";
  }
  const node = schema as Record<string, unknown>;

  if (Array.isArray(node["enum"])) {
    const members = node["enum"].map((value) => JSON.stringify(value));
    return members.length > 0 ? unionOf(members) : "never";
  }

  const oneOf = node["oneOf"] ?? node["anyOf"];
  if (Array.isArray(oneOf) && oneOf.length > 0) {
    return unionOf(oneOf.map((member) => jsonSchemaToTs(member)));
  }

  const type = node["type"];
  if (Array.isArray(type)) {
    if (type.length === 0) return "unknown";
    return unionOf(
      type.map((t) => jsonSchemaToTs({ ...node, type: t as unknown }))
    );
  }

  switch (type) {
    case "string":
      return "string";
    case "number":
    case "integer":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    case "array": {
      const items = node["items"];
      return `Array<${items === undefined ? "unknown" : jsonSchemaToTs(items)}>`;
    }
    case "object":
      return objectToTs(node);
    default:
      return "unknown";
  }
}

function objectToTs(node: Record<string, unknown>): string {
  const properties = node["properties"];
  if (
    properties === null ||
    typeof properties !== "object" ||
    Array.isArray(properties) ||
    Object.keys(properties as object).length === 0
  ) {
    return "Record<string, unknown>";
  }

  const required = new Set(
    Array.isArray(node["required"])
      ? node["required"].filter((r): r is string => typeof r === "string")
      : []
  );

  const members = Object.entries(properties as Record<string, unknown>).map(
    ([key, propSchema]) => {
      const optional = required.has(key) ? "" : "?";
      return `${JSON.stringify(key)}${optional}: ${jsonSchemaToTs(propSchema)}`;
    }
  );

  return `{ ${members.join("; ")} }`;
}

function unionOf(members: string[]): string {
  const unique = [...new Set(members)];
  return unique.length === 1 ? (unique[0] as string) : unique.join(" | ");
}

/** A tool entry as printed by `bin/rails action_mcp:apps:schema`. */
export interface ToolSchema {
  name: string;
  inputSchema?: unknown;
  outputSchema?: unknown;
}

/**
 * Renders the `.action_mcp/types.d.ts` content: an `ActionMcpTools`
 * interface mapping tool name -> `{ input, output }` types.
 */
export function generateToolTypes(tools: ToolSchema[]): string {
  const lines: string[] = [
    "// Generated by @action-mcp/vite-plugin. Do not edit.",
    "",
    "export interface ActionMcpTools {",
  ];
  for (const tool of tools) {
    lines.push(`  ${JSON.stringify(tool.name)}: {`);
    lines.push(`    input: ${jsonSchemaToTs(tool.inputSchema)};`);
    lines.push(`    output: ${jsonSchemaToTs(tool.outputSchema)};`);
    lines.push("  };");
  }
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}
